### ISSUE TITLE
How do sidewalls mount

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-valdis#25]
What fastening stiles is used for the sidewalls? Currently they look bottom mounted. What holds them in place?

![image](https://user-images.githubusercontent.com/5435954/204098363-e02f2dc4-1ce2-4dea-9bda-575b0f278e8e.png)

**Comment by vinku34** [comment]
Bolts go through from the bottom and thread into a nyloc nut from the top.

**Comment by Akustav** [comment]
Hm okay. I guess
