### ISSUE TITLE
[Mechanics] blue lines in sketches

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-valdis#3]
Some sketches are left under defined. This can make it difficult to modify components later on and can create unpredictable situations when modifying things. This can be fixed by adding measurements to sketches until every line is black.

![image](https://user-images.githubusercontent.com/5435954/193412825-1dc45b90-d394-4645-b5ad-75efbd146826.png)

**Comment by vircoh** [comment]
Võiks olla korras

**Comment by Akustav** [comment]
Am I looking at the correct file? wall3 v15 has a lot of blue:
![image](https://user-images.githubusercontent.com/5435954/194118918-81612b84-41c6-48e3-9831-f9bfef1d9c28.png)

Ramp3 v4 has one hole underdefined:
![image](https://user-images.githubusercontent.com/5435954/194119067-37fb5704-5b35-4ee2-a9fd-7731a6439d43.png)
