### ISSUE TITLE
Mounting hole too close to components

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-valdis#38]
I added a cylinder with a diameter of 5.5 mm (same as M3 bolt head) on the PCB.

![image](https://user-images.githubusercontent.com/1595938/205370793-5fc18073-775f-429c-b1ba-d5d0f93a900c.png)

Other mounting hole is very close to the PCB edge:
![image](https://user-images.githubusercontent.com/1595938/205374654-5d33935e-5a52-4551-b355-10406b8a6d4c.png)

**Comment by ReikoR** [comment]
Other mounting hole might be too close to the motor output pads or might damage the solder mask and short the copper below.

![image](https://user-images.githubusercontent.com/1595938/205486807-860e73d7-200b-4333-9bc8-14317e3be9b1.png)

**Comment by vinku34** [comment]
Can I just keep the one mounting hole then? It won't be supporting much weight anyways.

**Comment by ReikoR** [comment]
It would be better to have at least 2 mounting holes to prevent the PCB from rotating.

There is room near the original location, it was just too close to the edge before. Silkscreen text needs to be moved. Silkscreen text can also be smaller if there is not enough room.

![image](https://user-images.githubusercontent.com/1595938/205489822-91c8532a-fc0a-4668-a41f-d053d92b7504.png)
